// <auto-generated/>
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("Colourful")]
[assembly: AssemblyDescriptionAttribute("Open source .NET library for working with color spaces.")]
[assembly: GuidAttribute("D11F6BE9-3DCB-45B7-A076-4D476236C3CB")]
[assembly: AssemblyProductAttribute("Colourful")]
[assembly: AssemblyVersionAttribute("1.1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0")]
[assembly: AssemblyCopyrightAttribute("Tomas Pazourek, 2015")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.0.0";
    }
}
