//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("Colourful")]
[assembly: AssemblyDescription("Open source .NET library for working with color spaces.")]
[assembly: AssemblyProduct("Colourful")]
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyInformationalVersion("0")]
[assembly: AssemblyCopyright("Copyright © Tomáš Pažourek, 2016")]
[assembly: Guid("D11F6BE9-3DCB-45B7-A076-4D476236C3CB")]
[assembly: CLSCompliant(true)]

